db:
 driver: org.h2.Driver
 url: jdbc:h2:mem:test
 username: sa
 password: 
 
hibernate:
 dialect: org.hibernate.dialect.H2Dialect
 format_sql: true
 hbm2ddl:
  auto: create-drop
 ejb:
  naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
 show_sql: false